// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlmfi_TMxJnEaPUyuuhBKP9m4IqT0K_ZQ',
    appId: '1:488723898339:web:97e482307668593a0e0ad6',
    messagingSenderId: '488723898339',
    projectId: 'news-app-38a39',
    authDomain: 'news-app-38a39.firebaseapp.com',
    storageBucket: 'news-app-38a39.appspot.com',
    measurementId: 'G-L6L58FR3QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbnpt0X7AAL3kyUkiHYyrR759vXl0Cths',
    appId: '1:488723898339:android:22f15917c09335ae0e0ad6',
    messagingSenderId: '488723898339',
    projectId: 'news-app-38a39',
    storageBucket: 'news-app-38a39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoQrJutWswQW_yx0QewtIAdT3nPsafI2I',
    appId: '1:488723898339:ios:57bff2c1a483d3360e0ad6',
    messagingSenderId: '488723898339',
    projectId: 'news-app-38a39',
    storageBucket: 'news-app-38a39.appspot.com',
    iosClientId: '488723898339-ru91poff6ruj42lm21t78kh1447v8rv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsAppStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoQrJutWswQW_yx0QewtIAdT3nPsafI2I',
    appId: '1:488723898339:ios:57bff2c1a483d3360e0ad6',
    messagingSenderId: '488723898339',
    projectId: 'news-app-38a39',
    storageBucket: 'news-app-38a39.appspot.com',
    iosClientId: '488723898339-ru91poff6ruj42lm21t78kh1447v8rv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsAppStore',
  );
}
